In [1]:
import pandas as pd

In [3]:
wind_df = pd.read_csv(r'data\punjab_wind_2021_2025.csv')
fire_df = pd.read_csv(r'data\punjab_fires_2021_2025.csv')
weather_df = pd.read_csv(r'data\delhi_weather_2021_2024.csv')
aq_df = pd.read_csv(r'data\delhi_aqi_2021_2024.csv')

In [15]:
wind_df.head()

,Latitude,Longitude,Data Acquisition Time,Telemetry Hourly Wind Speed (Km/Hr),acq_date
0,30.140833,74.207778,12-04-2021 18:57,40.4,2021-04-12
1,30.140833,74.207778,12-04-2021 19:57,38.0,2021-04-12
2,30.140833,74.207778,12-04-2021 20:57,35.6,2021-04-12
3,30.140833,74.207778,12-04-2021 21:57,34.4,2021-04-12
4,30.140833,74.207778,12-04-2021 22:57,30.8,2021-04-12

In [8]:
weather_df["DATE"] = pd.to_datetime(weather_df["DATE"]).dt.strftime("%Y-%m-%d")
weather_df.head()

,DATE,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,humidity,precip,precipprob,precipcover,windspeed,sealevelpressure,conditions,tempmax_humidity,tempmin_humidity,temp_humidity,temp_range,heat_index
0,2021-01-01,18.1,3.7,10.2,18.1,3.7,10.2,79.2,0.000,0,0.00,11.2,1017.9,Clear,1433.52,293.04,807.84,14.4,319.136909
1,2021-01-02,19.0,7.8,13.4,19.0,7.8,13.4,77.8,0.911,100,8.33,16.6,1016.1,"Rain, Partially cloudy",1478.20,606.84,1042.52,11.2,291.062565
2,2021-01-03,17.0,11.1,13.9,17.0,11.1,13.9,90.1,36.462,100,12.50,16.6,1014.6,"Rain, Partially cloudy",1531.70,1000.11,1252.39,5.9,286.708959
3,2021-01-04,21.6,12.2,16.2,21.6,12.2,16.2,94.2,5.598,100,12.50,18.4,1016.1,"Rain, Partially cloudy",2034.72,1149.24,1526.04,9.4,263.446575
4,2021-01-05,20.6,14.5,17.1,20.6,14.5,17.1,93.8,1.280,100,8.33,14.8,1015.5,"Rain, Partially cloudy",1932.28,1360.10,1603.98,6.1,256.187200

In [5]:
merge_1 = pd.merge(wind_df, fire_df, how='inner', on='acq_date')
merge_1.head()

,Latitude,Longitude,Data Acquisition Time,Telemetry Hourly Wind Speed (Km/Hr),acq_date,latitude,longitude,brightness,scan,track,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,dist_to_delhi
0,32.443262,75.731494,05-01-2024 10:00,0.0,2024-01-05,32.94955,75.80044,304.39,0.38,0.36,2044,N20,VIIRS,n,2,271.64,1.01,N,0,500.510645
1,32.443262,75.731494,05-01-2024 10:00,0.0,2024-01-05,32.49773,76.32416,305.43,0.39,0.36,2044,N20,VIIRS,n,2,272.84,0.89,N,0,440.088533
2,32.443262,75.731494,05-01-2024 10:00,0.0,2024-01-05,29.90984,74.94777,305.47,0.38,0.36,2045,N20,VIIRS,n,2,279.77,0.79,N,2,262.441335
3,32.443262,75.731494,05-01-2024 11:00,0.0,2024-01-05,32.94955,75.80044,304.39,0.38,0.36,2044,N20,VIIRS,n,2,271.64,1.01,N,0,500.510645
4,32.443262,75.731494,05-01-2024 11:00,0.0,2024-01-05,32.49773,76.32416,305.43,0.39,0.36,2044,N20,VIIRS,n,2,272.84,0.89,N,0,440.088533

In [16]:
merge_2 = pd.merge(merge_1, weather_df, how='inner', left_on='acq_date', right_on='DATE')
merge_2.drop(columns=['Data Acquisition Time', 'DATE'], inplace=True)
merge_2.head()

,Latitude,Longitude,Telemetry Hourly Wind Speed (Km/Hr),acq_date,latitude,longitude,brightness,scan,track,acq_time,...,precipprob,precipcover,windspeed,sealevelpressure,conditions,tempmax_humidity,tempmin_humidity,temp_humidity,temp_range,heat_index
0,32.443262,75.731494,0.0,2024-01-05,32.94955,75.80044,304.39,0.38,0.36,2044,...,0,0.0,11.2,1018.2,Partially cloudy,1300.6,929.0,1114.8,4.0,302.174724
1,32.443262,75.731494,0.0,2024-01-05,32.49773,76.32416,305.43,0.39,0.36,2044,...,0,0.0,11.2,1018.2,Partially cloudy,1300.6,929.0,1114.8,4.0,302.174724
2,32.443262,75.731494,0.0,2024-01-05,29.90984,74.94777,305.47,0.38,0.36,2045,...,0,0.0,11.2,1018.2,Partially cloudy,1300.6,929.0,1114.8,4.0,302.174724
3,32.443262,75.731494,0.0,2024-01-05,32.94955,75.80044,304.39,0.38,0.36,2044,...,0,0.0,11.2,1018.2,Partially cloudy,1300.6,929.0,1114.8,4.0,302.174724
4,32.443262,75.731494,0.0,2024-01-05,32.49773,76.32416,305.43,0.39,0.36,2044,...,0,0.0,11.2,1018.2,Partially cloudy,1300.6,929.0,1114.8,4.0,302.174724

In [ ]:

merge_2.columns

Index(['Latitude', 'Longitude', 'Telemetry Hourly Wind Speed (Km/Hr)',
       'acq_date', 'latitude', 'longitude', 'brightness', 'scan', 'track',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_t31', 'frp', 'daynight', 'type', 'dist_to_delhi', 'tempmax',
       'tempmin', 'temp', 'feelslikemax', 'feelslikemin', 'feelslike',
       'humidity', 'precip', 'precipprob', 'precipcover', 'windspeed',
       'sealevelpressure', 'conditions', 'tempmax_humidity',
       'tempmin_humidity', 'temp_humidity', 'temp_range', 'heat_index'],
      dtype='object')

In [11]:
len(fire_df)

48902

In [12]:
fire_df.head()

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type,dist_to_delhi
0,32.42054,76.44252,347.59,0.38,0.36,2024-01-01,756,N20,VIIRS,n,2,289.27,11.36,D,0,429.595104
1,32.41993,76.43851,352.37,0.38,0.36,2024-01-01,756,N20,VIIRS,n,2,308.38,17.32,D,0,429.594092
2,32.42319,76.43782,329.83,0.38,0.36,2024-01-01,756,N20,VIIRS,n,2,285.61,17.32,D,0,429.962328
3,32.42258,76.43382,342.17,0.38,0.36,2024-01-01,756,N20,VIIRS,n,2,300.39,17.32,D,0,429.961505
4,32.60556,76.29498,326.37,0.38,0.36,2024-01-01,756,N20,VIIRS,n,2,285.61,4.91,D,0,452.382469